# Generated by Django 2.2.6 on 2019-10-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='name',
        ),
        migrations.AddField(
            model_name='snippet',
            name='Search',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
